# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChuRemacor
                                 A QGIS plugin
 Remacor extentsion
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-06
        copyright            : (C) 2022 by Arnaud Vandecasteele - arnaud.vdc@geolab.re
        email                : arnaud.vdc@geolab.re
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ChuRemacor class from file ChuRemacor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .churemacor import ChuRemacor
    return ChuRemacor(iface)
